[package]
name = "battery-osd"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.10"
gtk4-layer-shell = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
anyhow = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
